### ISSUE TITLE
SNES Compatibility

### ISSUE THREAD

**Issue by PikachuR77** [RocketRobz/TWiLightMenu#37] opened 2018-05-09 16:41 UTC
It would be nice to have SNES compatibility throguh SNEmulDS. It seems to have the best compatibility.

**Comment by Robz8** [comment] 2018-05-09 20:16
Is there an SNES emulator that works on SD card, though?
If not, should be possible to get SNEmulDS working from SD card, but that'd require a manual patch for bootstrap.

**Comment by ahezard** [comment] 2018-05-17 15:32
I did some investigation on why snesmulds is not working with nds-bootstrap (homebrew/dldi branch).
I looked at the code maintained by coto here : https://github.com/cotodevel/SnemulDS
The issue is that SNEmulDS is not based on devkitarm/libnds  but on another toolkit : ToolchainGenericDS.
In order to make the dldi works nds-bootstrap is patching specific libnds code into the arm7 binary that have never changes from the first libnds release to the last release : https://github.com/devkitPro/libnds/blob/master/source/common/interruptDispatcher.s
So any homebrew not using libnds are not compatible currently.

What should be possible is to add a patch into nds-bootstrap for this ToolchainGenericDS toolkit. The code to tqrget should be here https://github.com/cotodevel/ToolchainGenericDS/blob/master/src/common/hardware/InterruptsARMCores_c.c

**Comment by NightYoshi370** [comment] 2018-09-06 03:05
For the meanwhile, why not try implementing lolsnes?

**Comment by lenix9090** [comment] 2018-10-11 20:56
"lolSnes"It does not work ... a white screen appears that does not do anything ... the good thing is that it does not give a bigger error to that.

Google translator

**Comment by NightYoshi370** [comment] 2019-01-21 05:55
UPDATE: We can now use SNEmulDS on TWiLightMenu++. Therefore, I'll be closing this.

**Closed by NightYoshi370** 2019-01-21 05:55 UTC
Labels: request
