### ISSUE TITLE
Guru Meditation Error after selecting Akmenu's "black" menu theme

### ISSUE THREAD

**Issue by SegaSystem16C** [RocketRobz/TWiLightMenu#220] opened 2018-09-20 12:50 UTC
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)

This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

- [x ]  Release Version 2.0.2
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x ]  Release Version 6.2.1
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Set AkMenu "black" menu theme and use the program with this selected UI.

### Actual behaviour

After saving the settings, the program displays a "Guru Meditation Error" red screen on the lower screen.
Turning off the console and booting DSiMenu++ again prompts to the same error screen.

### Steps to reproduce

1. Select Akmenu  theme, and "Black" subtheme;
2. Press B to go back, save settings and reboot the program;
3. Boot DSiMenu++ after setting akmenu "black" as menu theme.

**Comment by dubbz82** [comment] 2018-09-20 13:00
Dupe of #209 I believe?

**Comment by SegaSystem16C** [comment] 2018-09-20 13:33
> Dupe of #209 I believe?

No. I just got this error last night when i was testing other menu skins. Searched for this, but didn't found anything related to this. So i came here to report it. I didn't knew another person had the same problem.

**Comment by Robz8** [comment] 2018-09-23 00:09
The error appears to be caused by having a 3DS cart in the slot.

**Comment by SegaSystem16C** [comment] 2018-09-27 02:47
> The error appears to be caused by having a 3DS cart in the slot.

Yeah, i remember i had a cart of Super Mario 3D Land inserted when i had this error. Deleting settings.ini fixed the problem and i got to boot into the Akmenu Theme (even with the cart inserted).

**Comment by Robz8** [comment] 2018-09-27 02:50
It now works with a 3DS cart inserted, because the launcher tells TWiLight Menu++ that such cart is inserted, so that Acekard theme doesn't attempt to read it, and doesn't crash as a result.
However, the crash is still caused by some flashcards (and retail carts?).

**Comment by NightYoshi370** [comment] 2018-12-19 04:21
@RocketRobz is this fixed in the latest version?

**Comment by RocketRobz** [comment] 2018-12-19 04:40
Yes.

**Closed by RocketRobz** 2018-12-19 04:40 UTC
Labels: akmenu Theme
